### PR TITLE
Convert PNG in mode CMYK Fix

### PR DESCRIPTION
**Pull request by stanpresshook**
## Summary
This PR fixes issue #106 where PNG writing fails if the image is in mode CMYK.

## Fix
Add check following the same format as `save_as_jpeg` where we convert the image to `RGB` mode if the current mode is `CMYK`

### CODE REVIEW

**Comment by zerolab** [comment]
Would be great to get a small sample image and have a test for it.

**Comment by stanpresshook** [comment]
@zerolab test added!

**Comment by kaedroho** [comment]
@stanpresshook thanks a lot for this, the code looks good to me but the test is currently failing. Please could you look into that, I'd be happy to merge this once it's fixed!

**Comment by zerolab** [comment]
closing in favour of #123 (which rebases on `main` and tidies up the code)

**Pull request closed without merging**
