### PR TITLE
Proposal: Add support for TIFF

### PR DESCRIPTION
**Pull request by maikhoepfel**
I recently needed to add TIFF support to a Wagtail installation. Luckily, very little was needed to get it working - it's a format that's very close to BMP. I see you already have support for BMP, so if you like, you're welcome to pick my changes across. 
Please understand this PR as a "I'm not sure if you're interested" - I'm happy to update this according to your guidelines and with a bit of documentation should you be interested in merging this.

I assume that Wagtail has it's reasons for not allowing more "print-ey" formats like BMP. Again, [very little](https://github.com/maikhoepfel/wagtail/commits/bmp-tiff-support) is needed to get it working - again, let me know if you'd like me to prepare a pull request.

### CODE REVIEW

**Comment by kaedroho** [comment]
I think this would be good to have in Willow. Looks like it just needs docs and tests, thanks for working on this!

**Comment by balazs-endresz** [comment]
This might be relevant with Wagtail only but what happens if you display the original tiff or bmp on a website? Is that going to show the original (presumably quite large) bmp/tiff file or a jpeg rendition in the original size?

**Comment by kaedroho** [comment]
@balazs-endresz The behaviour at the moment is to convert BMP files to PNG format. This happens on the ``original`` filter as well as that filter always creates a new rendition anyway.

I expect we would use the same behaviour for TIFF files as well.

**Comment by maikhoepfel** [comment]
I'm glad you like it. I'll prep a full pull request then. 

@balazs-endresz Yeah, on the Wagtail side of things, I got things working exactly like @kaedroho said. See the second commit [here](https://github.com/maikhoepfel/wagtail/commits/bmp-tiff-support).

**Comment by maikhoepfel** [comment]
Hi everyone, I've added some tests. I didn't find a place in the documentation where we document all supported image formats, so I've left it for you to decide. 

Please note that I don't actually understand a lot of what I did there - I was just guessing by the surrounding code. Please sanity-check it ;) Having said that, it works for me in a project.

Thanks for a cool project!

**Comment by maikhoepfel** [comment]
Hey hey, I fully appreciate you have bigger things to worry about than this PR. Just wanted to let you know that the project I did this for is running for another two weeks - afterwards I might not be able to react to changes you'd like to see from me.

**Comment by tomdyson** [comment]
ping @kaedroho - this looks good to me, are you happy with it?

**Comment by kaedroho** [comment]
Just been looking through it right now. All looks goot to me!

**Comment by maikhoepfel** [comment]
Cool, thanks Karl and Tom!

**Pull request merged**
